wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.12
    start_time: 1661799556.386536
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 13
      - 14
      - 16
      - 23
      4: 3.9.12
      5: 0.13.2
      8:
      - 4
      - 5
created_at:
  desc: null
  value: '2022-08-29T11:24:48'
fine_tuned_model:
  desc: null
  value: davinci:ft-personal-2022-08-29-18-28-43
hyperparams:
  desc: null
  value:
    batch_size: 1
    learning_rate_multiplier: 0.1
    n_epochs: 4
    prompt_loss_weight: 0.1
id:
  desc: null
  value: ft-5kJ8K87PnNbDBT3CDXX0iHEE
model:
  desc: null
  value: davinci
n_train:
  desc: null
  value: 19
object:
  desc: null
  value: fine-tune
organization_id:
  desc: null
  value: org-UQAqGjWYD9fRg5PJebJV7gkt
result_files:
  desc: null
  value:
    bytes: 3607
    created_at: 1661797724
    filename: compiled_results.csv
    id: file-iHfFTAZLAnLJJOMSCEmg2x9B
    object: file
    purpose: fine-tune-results
    status: processed
    status_details: null
status:
  desc: null
  value: succeeded
training_files:
  desc: null
  value:
    bytes: 1561
    created_at: 1661797488
    filename: association_data_prepared.jsonl
    id: file-YVc3Io3NGgf8fXFjzzlJxKb9
    object: file
    purpose: fine-tune
    status: processed
    status_details: null
updated_at:
  desc: null
  value: 1661797724
validation_files:
  desc: null
  value: []
